import './globals.css'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react'
import MantineProvider from './hooks/MantineProvider'


const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Fam Tools',
  description: 'Generated by create next app',
}


export default function RootLayout({children }: {children: ReactNode}) {

  return (
    <html lang="en" style={{ opacity: 0 }}>
      <body>
        <MantineProvider>
          {children}
        </MantineProvider>
     </body>
    </html>
  )
}
